### ISSUE TITLE
[Feature Request]: Timed effects

### ISSUE THREAD

**Issue by Addaadostuff** [quellus/GDTuber#116]
### Is your feature request related to a problem? Please describe.

set up timer to replace displayobject for N - Time

### Describe the solution you'd like

Create a tab for config to displayobjects settings 
settings:
> time 
>  object to replace 

Add an button to start replacing.

replacing:

>  hide selected object 
> show object this object

after timer is up, switch back to orginal state.

### Additional Context

Feel free to correct my grammar.

**Comment by quellus** [comment]
Basically, we want the ability to hide a screen object and show a different screen object for a certain amount of time. For example, I have an event on my stream where I hide my main avatar, and replace it with a secondary avatar for 10 minutes. Automating this would make my life a lot easier because I keep forgetting to change it back 10 minutes later.

**Comment by dohro-github** [comment]
I'm working on that right now for the GDTuber 0.11 update
