### ISSUE TITLE
Implement Twitcher

### ISSUE THREAD

**Issue by quellus** [quellus/GDTuber#12]
We want avatars to react to events from Twitch. The main priority is viewer rewards, but some users may want chat commands as well.

This issue is just to create a prototype of Twitcher causing something to happen. Even if that's as little as just a print to the console when a reward is redeemed.

https://godotengine.org/asset-library/asset/2629

**Comment by spaghetticodefactory** [comment]
I think that implementing Twitcher instead of providing a generic HTTP API would cause more work and a bigger codebase in the future, because people who are multistreaming or streaming on other platforms like YouTube won't be able to use it.

My proposal would be to provide a boilerplate HTTP API integration that can be used by everyone with tools like Streamer Bot

**Comment by quellus** [comment]
Maybe this change is too specific to me and not something other users are likely to want? If that’s the case, I should make a fork add this feature there
